name: Test, build and publish

on:
  push:
    branches:
      - master

env:
  CI: true
jobs:
  test-build-publish:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'
          cache: 'npm'
          registry-url: https://npm.pkg.github.com
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Publish
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
